services:
  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
  
  db: 
    image: mongo
    container_name: mongo_db
    ports:
      - 27018:27017
    volumes:
      - db_data:/var/lib/mongo
  

  # pg: 
  #   image: postgres
  #   container_name: pg_db
  #   ports:
  #     - 5000:5432
  #   environment:
  #     - POSTGRES_PASSWORD=1234
  #   volumes:
  #     - db_data_pg:/var/lib/pg

volumes:
  db_data:
  # db_data_pg:
